// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.canvas;

import jakarta.faces.annotation.ManagedProperty;
import jakarta.inject.Inject;
import org.primefaces.PrimeFaces;
import java.util.Map;

public class JSRemoteController {
    @Inject
    @ManagedProperty("#{facesContext.externalContext.requestParameterMap}")
    private Map<String, String> params;

    protected String getParam(String name) {
        return params.getOrDefault(name, null);
    }

    protected void sendParam(String name, Object value) {
        PrimeFaces.current().ajax().addCallbackParam(name, value);
    }

    @java.lang.SuppressWarnings("all")
    public void setParams(final Map<String, String> params) {
        this.params = params;
    }
}
