// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.check;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import ru.bardinpetr.itmo.lab3.data.dto.AreaConfigDTO;
import ru.bardinpetr.itmo.lab3.data.models.AreaConfig;
import ru.bardinpetr.itmo.lab3.data.models.Point;
import java.io.Serializable;
import java.util.function.Predicate;

@Named("areaPolygonController")
@SessionScoped
public class AreaPolygonController implements Serializable {
    @Inject
    private PointCheckPredicate checkInsidePredicate;
    @Inject
    private AreaConfigDTO areaConfigDTO;

    public AreaConfig getAreaConfig() {
        return AreaConfig.of(areaConfigDTO.getR());
    }

    public Predicate<Point> getPredicate() {
        if (checkInsidePredicate == null || areaConfigDTO == null) return null;
        return (Point x) -> checkInsidePredicate.test(x.scale(1 / areaConfigDTO.getR()));
    }

    @java.lang.SuppressWarnings("all")
    public AreaPolygonController() {
    }

    @java.lang.SuppressWarnings("all")
    public PointCheckPredicate getCheckInsidePredicate() {
        return this.checkInsidePredicate;
    }

    @java.lang.SuppressWarnings("all")
    public AreaConfigDTO getAreaConfigDTO() {
        return this.areaConfigDTO;
    }

    @java.lang.SuppressWarnings("all")
    public void setCheckInsidePredicate(final PointCheckPredicate checkInsidePredicate) {
        this.checkInsidePredicate = checkInsidePredicate;
    }

    @java.lang.SuppressWarnings("all")
    public void setAreaConfigDTO(final AreaConfigDTO areaConfigDTO) {
        this.areaConfigDTO = areaConfigDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AreaPolygonController)) return false;
        final AreaPolygonController other = (AreaPolygonController) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$checkInsidePredicate = this.getCheckInsidePredicate();
        final java.lang.Object other$checkInsidePredicate = other.getCheckInsidePredicate();
        if (this$checkInsidePredicate == null ? other$checkInsidePredicate != null : !this$checkInsidePredicate.equals(other$checkInsidePredicate)) return false;
        final java.lang.Object this$areaConfigDTO = this.getAreaConfigDTO();
        final java.lang.Object other$areaConfigDTO = other.getAreaConfigDTO();
        if (this$areaConfigDTO == null ? other$areaConfigDTO != null : !this$areaConfigDTO.equals(other$areaConfigDTO)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AreaPolygonController;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $checkInsidePredicate = this.getCheckInsidePredicate();
        result = result * PRIME + ($checkInsidePredicate == null ? 43 : $checkInsidePredicate.hashCode());
        final java.lang.Object $areaConfigDTO = this.getAreaConfigDTO();
        result = result * PRIME + ($areaConfigDTO == null ? 43 : $areaConfigDTO.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AreaPolygonController(checkInsidePredicate=" + this.getCheckInsidePredicate() + ", areaConfigDTO=" + this.getAreaConfigDTO() + ")";
    }
}
