// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.data.util;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Named;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Persistence;
import jakarta.persistence.criteria.CriteriaBuilder;
import java.io.Serializable;

@Named("entityManagerProvider")
@ApplicationScoped
public class EntityManagerProvider implements Serializable {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(EntityManagerProvider.class);
    private EntityManager entityManager;
    private CriteriaBuilder criteriaBuilder;

    @PostConstruct
    public void init() {
        entityManager = Persistence.createEntityManagerFactory("lab3").createEntityManager();
        criteriaBuilder = entityManager.getCriteriaBuilder();
        log.info("Initialized entity manager provider");
    }

    @java.lang.SuppressWarnings("all")
    public EntityManagerProvider() {
    }

    @java.lang.SuppressWarnings("all")
    public EntityManager getEntityManager() {
        return this.entityManager;
    }

    @java.lang.SuppressWarnings("all")
    public CriteriaBuilder getCriteriaBuilder() {
        return this.criteriaBuilder;
    }

    @java.lang.SuppressWarnings("all")
    public void setEntityManager(final EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    @java.lang.SuppressWarnings("all")
    public void setCriteriaBuilder(final CriteriaBuilder criteriaBuilder) {
        this.criteriaBuilder = criteriaBuilder;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EntityManagerProvider)) return false;
        final EntityManagerProvider other = (EntityManagerProvider) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$entityManager = this.getEntityManager();
        final java.lang.Object other$entityManager = other.getEntityManager();
        if (this$entityManager == null ? other$entityManager != null : !this$entityManager.equals(other$entityManager)) return false;
        final java.lang.Object this$criteriaBuilder = this.getCriteriaBuilder();
        final java.lang.Object other$criteriaBuilder = other.getCriteriaBuilder();
        if (this$criteriaBuilder == null ? other$criteriaBuilder != null : !this$criteriaBuilder.equals(other$criteriaBuilder)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EntityManagerProvider;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $entityManager = this.getEntityManager();
        result = result * PRIME + ($entityManager == null ? 43 : $entityManager.hashCode());
        final java.lang.Object $criteriaBuilder = this.getCriteriaBuilder();
        result = result * PRIME + ($criteriaBuilder == null ? 43 : $criteriaBuilder.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "EntityManagerProvider(entityManager=" + this.getEntityManager() + ", criteriaBuilder=" + this.getCriteriaBuilder() + ")";
    }
}
