// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.auth.jwt.models;

import java.util.Arrays;

public enum JWTType {
    ACCESS(60 * 60, "kid-access", "app"), REFRESH(60 * 60, "kid-refresh", "app-auth");
    private final int expiry;
    private final String kid;
    private final String aud;

    public static JWTType byKid(String kid) {
        return Arrays.stream(JWTType.values()).filter(i -> i.kid.equals(kid)).findFirst().orElseThrow();
    }

    @java.lang.SuppressWarnings("all")
    private JWTType(final int expiry, final String kid, final String aud) {
        this.expiry = expiry;
        this.kid = kid;
        this.aud = aud;
    }

    @java.lang.SuppressWarnings("all")
    public int getExpiry() {
        return this.expiry;
    }

    @java.lang.SuppressWarnings("all")
    public String getKid() {
        return this.kid;
    }

    @java.lang.SuppressWarnings("all")
    public String getAud() {
        return this.aud;
    }
}
