// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.auth.jwt.keys.impl;

import jakarta.enterprise.context.ApplicationScoped;
import ru.bardinpetr.itmo.lab3.app.auth.jwt.models.JWTType;

@ApplicationScoped
public class AppKeyStorage extends JWTHMACKeyProvider {
    public AppKeyStorage() {
        registerGenerate(JWTType.ACCESS.getKid());
        registerGenerate(JWTType.REFRESH.getKid());
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AppKeyStorage)) return false;
        final AppKeyStorage other = (AppKeyStorage) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AppKeyStorage;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int result = 1;
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AppKeyStorage()";
    }
}
