// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.auth.jwt.payload;

import jakarta.security.enterprise.CallerPrincipal;
import ru.bardinpetr.itmo.lab3.app.auth.jwt.models.JWTType;
import java.util.Set;

public class JWTCallerPrincipal extends CallerPrincipal {
    private final Set<String> groups;
    private final JWTType type;

    public JWTCallerPrincipal(String name, Set<String> groups, JWTType tokenType) {
        super(name);
        this.groups = groups;
        this.type = tokenType;
    }

    @java.lang.SuppressWarnings("all")
    public Set<String> getGroups() {
        return this.groups;
    }

    @java.lang.SuppressWarnings("all")
    public JWTType getType() {
        return this.type;
    }
}
