// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.data.dto;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import ru.bardinpetr.itmo.lab3.data.validators.range.RangeExternalValidated;
import java.io.Serializable;
import java.util.Set;
import static ru.bardinpetr.itmo.lab3.app.check.models.PointConstraints.ConstraintType;

@Named("areaConfig")
@SessionScoped
public class AreaConfigDTO implements Serializable {
    @RangeExternalValidated(ConstraintType.R)
    private Double r;

    @PostConstruct
    void init() {
        r = 2.0;
    }

    public Set<ConstraintViolation<AreaConfigDTO>> validate() {
        try (var factory = Validation.buildDefaultValidatorFactory()) {
            return factory.getValidator().validate(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    public AreaConfigDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Double getR() {
        return this.r;
    }

    @java.lang.SuppressWarnings("all")
    public void setR(final Double r) {
        this.r = r;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AreaConfigDTO)) return false;
        final AreaConfigDTO other = (AreaConfigDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$r = this.getR();
        final java.lang.Object other$r = other.getR();
        if (this$r == null ? other$r != null : !this$r.equals(other$r)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AreaConfigDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $r = this.getR();
        result = result * PRIME + ($r == null ? 43 : $r.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AreaConfigDTO(r=" + this.getR() + ")";
    }
}
