// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.data.models;

import jakarta.persistence.Embeddable;
import java.io.Serializable;

@Embeddable
public class AreaConfig implements Serializable {
    public static Double EPSILON = 1.0E-6;
    private Double r;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AreaConfig that = (AreaConfig) o;
        return Math.abs(r - that.r) < EPSILON;
    }

    public static AreaConfig of(Double r) {
        var x = new AreaConfig();
        x.setR(r);
        return x;
    }

    @java.lang.SuppressWarnings("all")
    public AreaConfig() {
    }

    @java.lang.SuppressWarnings("all")
    public Double getR() {
        return this.r;
    }

    @java.lang.SuppressWarnings("all")
    public void setR(final Double r) {
        this.r = r;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AreaConfig(r=" + this.getR() + ")";
    }
}
