// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.data.models;

import jakarta.persistence.Embeddable;
import jakarta.validation.constraints.NotNull;
import java.io.Serializable;

@Embeddable
public class Point implements Serializable {
    @NotNull
    private Double x;
    @NotNull
    private Double y;

    public Point scale(Double factor) {
        return Point.of(x * factor, y * factor);
    }

    public static Point of(@NotNull Double x, @NotNull Double y) {
        return new Point(x, y);
    }

    @java.lang.SuppressWarnings("all")
    public Double getX() {
        return this.x;
    }

    @java.lang.SuppressWarnings("all")
    public Double getY() {
        return this.y;
    }

    @java.lang.SuppressWarnings("all")
    public void setX(final Double x) {
        this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    public void setY(final Double y) {
        this.y = y;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Point)) return false;
        final Point other = (Point) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$x = this.getX();
        final java.lang.Object other$x = other.getX();
        if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
        final java.lang.Object this$y = this.getY();
        final java.lang.Object other$y = other.getY();
        if (this$y == null ? other$y != null : !this$y.equals(other$y)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Point;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $x = this.getX();
        result = result * PRIME + ($x == null ? 43 : $x.hashCode());
        final java.lang.Object $y = this.getY();
        result = result * PRIME + ($y == null ? 43 : $y.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Point(x=" + this.getX() + ", y=" + this.getY() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Point() {
    }

    @java.lang.SuppressWarnings("all")
    private Point(final Double x, final Double y) {
        this.x = x;
        this.y = y;
    }
}
