// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.data.models;

import jakarta.persistence.*;
import java.io.Serializable;
import java.time.Duration;
import java.time.LocalDateTime;

@Entity
@Table(name = "point_result")
public class PointResult implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Embedded
    private Point point;
    @Embedded
    private AreaConfig area;
    @Column(nullable = false)
    private Boolean isInside;
    @Column(nullable = false)
    private LocalDateTime timestamp;
    @Column(nullable = false)
    private Duration executionTime;

    @java.lang.SuppressWarnings("all")
    public PointResult() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Point getPoint() {
        return this.point;
    }

    @java.lang.SuppressWarnings("all")
    public AreaConfig getArea() {
        return this.area;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsInside() {
        return this.isInside;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public Duration getExecutionTime() {
        return this.executionTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setPoint(final Point point) {
        this.point = point;
    }

    @java.lang.SuppressWarnings("all")
    public void setArea(final AreaConfig area) {
        this.area = area;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsInside(final Boolean isInside) {
        this.isInside = isInside;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimestamp(final LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setExecutionTime(final Duration executionTime) {
        this.executionTime = executionTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PointResult)) return false;
        final PointResult other = (PointResult) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$isInside = this.getIsInside();
        final java.lang.Object other$isInside = other.getIsInside();
        if (this$isInside == null ? other$isInside != null : !this$isInside.equals(other$isInside)) return false;
        final java.lang.Object this$point = this.getPoint();
        final java.lang.Object other$point = other.getPoint();
        if (this$point == null ? other$point != null : !this$point.equals(other$point)) return false;
        final java.lang.Object this$area = this.getArea();
        final java.lang.Object other$area = other.getArea();
        if (this$area == null ? other$area != null : !this$area.equals(other$area)) return false;
        final java.lang.Object this$timestamp = this.getTimestamp();
        final java.lang.Object other$timestamp = other.getTimestamp();
        if (this$timestamp == null ? other$timestamp != null : !this$timestamp.equals(other$timestamp)) return false;
        final java.lang.Object this$executionTime = this.getExecutionTime();
        final java.lang.Object other$executionTime = other.getExecutionTime();
        if (this$executionTime == null ? other$executionTime != null : !this$executionTime.equals(other$executionTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PointResult;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $isInside = this.getIsInside();
        result = result * PRIME + ($isInside == null ? 43 : $isInside.hashCode());
        final java.lang.Object $point = this.getPoint();
        result = result * PRIME + ($point == null ? 43 : $point.hashCode());
        final java.lang.Object $area = this.getArea();
        result = result * PRIME + ($area == null ? 43 : $area.hashCode());
        final java.lang.Object $timestamp = this.getTimestamp();
        result = result * PRIME + ($timestamp == null ? 43 : $timestamp.hashCode());
        final java.lang.Object $executionTime = this.getExecutionTime();
        result = result * PRIME + ($executionTime == null ? 43 : $executionTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PointResult(id=" + this.getId() + ", point=" + this.getPoint() + ", area=" + this.getArea() + ", isInside=" + this.getIsInside() + ", timestamp=" + this.getTimestamp() + ", executionTime=" + this.getExecutionTime() + ")";
    }
}
