// Generated by delombok at Thu May 09 13:42:06 MSK 2024
package ru.bardinpetr.itmo.lab3.app.canvas.dto;

import ru.bardinpetr.itmo.lab3.data.models.PointResult;
import java.io.Serializable;

public class CanvasPointResult implements Serializable {
    private Double x;
    private Double y;
    private Double r;
    private Boolean inside;

    public static CanvasPointResult of(PointResult src) {
        var res = new CanvasPointResult();
        res.setX(src.getPoint().getX());
        res.setY(src.getPoint().getY());
        res.setR(src.getArea().getR());
        res.setInside(src.getIsInside());
        return res;
    }

    @java.lang.SuppressWarnings("all")
    public CanvasPointResult() {
    }

    @java.lang.SuppressWarnings("all")
    public Double getX() {
        return this.x;
    }

    @java.lang.SuppressWarnings("all")
    public Double getY() {
        return this.y;
    }

    @java.lang.SuppressWarnings("all")
    public Double getR() {
        return this.r;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getInside() {
        return this.inside;
    }

    @java.lang.SuppressWarnings("all")
    public void setX(final Double x) {
        this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    public void setY(final Double y) {
        this.y = y;
    }

    @java.lang.SuppressWarnings("all")
    public void setR(final Double r) {
        this.r = r;
    }

    @java.lang.SuppressWarnings("all")
    public void setInside(final Boolean inside) {
        this.inside = inside;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CanvasPointResult)) return false;
        final CanvasPointResult other = (CanvasPointResult) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$x = this.getX();
        final java.lang.Object other$x = other.getX();
        if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
        final java.lang.Object this$y = this.getY();
        final java.lang.Object other$y = other.getY();
        if (this$y == null ? other$y != null : !this$y.equals(other$y)) return false;
        final java.lang.Object this$r = this.getR();
        final java.lang.Object other$r = other.getR();
        if (this$r == null ? other$r != null : !this$r.equals(other$r)) return false;
        final java.lang.Object this$inside = this.getInside();
        final java.lang.Object other$inside = other.getInside();
        if (this$inside == null ? other$inside != null : !this$inside.equals(other$inside)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CanvasPointResult;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $x = this.getX();
        result = result * PRIME + ($x == null ? 43 : $x.hashCode());
        final java.lang.Object $y = this.getY();
        result = result * PRIME + ($y == null ? 43 : $y.hashCode());
        final java.lang.Object $r = this.getR();
        result = result * PRIME + ($r == null ? 43 : $r.hashCode());
        final java.lang.Object $inside = this.getInside();
        result = result * PRIME + ($inside == null ? 43 : $inside.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CanvasPointResult(x=" + this.getX() + ", y=" + this.getY() + ", r=" + this.getR() + ", inside=" + this.getInside() + ")";
    }
}
